version: "3"
services:
    webapp:
      build: ./webapp/.
      depends_on:
        - database
      ports:
        - "80:80"
      restart: 'always'
      volumes:
        - ./webapp/content:/var/www/html
      
    database:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: 12345
      restart: 'always'
      hostname: database
      volumes:
        - ./database/initialisation:/docker-entrypoint-initdb.d

    adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080
      environment:
        ADMINER_DEFAULT_SERVER: database
      depends_on:
        - database
